###############################################
#    Name: Starhip Promote Configuration      #                                       
#    Author: Prometheus                       #
#    Version: 3.0                             #
#    Description: StarShip Promote            #                
###############################################



# Inserts a blank line between shell prompts
add_newline = true

# Change the default prompt format
format = """\
[â•­â•´](238)$shell\
$all(238)$character"""

[env_var.STARSHIP_DISTRO]
format = '[$env_value](bold white)'  
variable = "STARSHIP_DISTRO"
disabled = false

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style) "
disabled = true  # disable in powershell
show_always = false

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "ğŸ”Œ"
discharging_symbol = "âš¡"

[[battery.display]]
threshold = 30
style = "bold red"

[character]
success_symbol = "[â¯](bold green)" 
error_symbol = "[âœ–](bold red) "

[cmd_duration]
min_time = 10_000  
format = " took [$duration]($style)"

[directory]
truncation_length = 5
format = "[$path]($style)[$lock_symbol]($lock_style) "
read_only = " ï ½"

# # Here is how you can shorten some long paths by text replacement
# # similar to mapped_locations in Oh My Posh:
[directory.substitutions]
# Home Folders Icons 
"~" = "ï€•"
"Desktop" = "ï„ˆ "
"Downloads" = "ï’˜ "
"Documents" = "ïœ˜ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "
"Videos" = "ï€½ "
"Templates" = "ïƒ… "
"Public" = "ï« "

# Other Folders Icons
"Games" = "ğŸ®"
"nvim" = " îŸ… "
".config" = "ï¥ "
"code" = "ï„¡ "
"GitHub-Projects" = "ïˆ "
# "GitHub" = "ïˆ "
"scripts" = "ï’‰ "

# Document Repo
"Testing-Repo" = "ïˆ î«„ "
"ISO" = "ï’"

# Tar and Zip Files
"unzip" = "ï‡† "
"zip" = "ï‡† "
"tar" = "ï‡† "
"tar.gz" = "ï‡† "
"tar.xz" = "ï‡† "
"tar.bz2" = "ï‡† "
"tar.zst" = "ï‡† "
"tar.lz" = "ï‡† "
"tar.lzma" = "ï‡† "

# main system folder
"etc" = "ï» "
"bin" = "ï„  "
"boot" = "ï…¼ "
"dev" = "ï‡¼ "
"home" = "ï€• "
"lib" = "ï†œ "
"lib64" = "ï†œ "
"media" = "ï€½ "
"mnt" = "ï‡€ "
"opt" = "ïƒ§ "
"proc" = "ï‹› "
"root" = "ïƒˆ "
"run" = "ï‡  "
"sbin" = "ï„  "
"srv" = "ïº "
"sys" = "ïƒ‰ "
"tmp" = "ï‡€ "
"usr" = "ï†’ "
"var" = "ï¼ "

# Web Development
"web-development" = "ï„»"
"css" = "ï„¼"
javascript = "ï¹"
nodejs="ï“"

# Android Studio
"Android" = "ï…» "
"Android-Studio" = "ï…» "
"Android-SDK" = "ï…» "
"Android-Projects" = "ï…» "
"Android-Emulator" = "ï…» "
"Android-SDK-Tools" = "ï…» "
"Android-SDK-Tools-Bin" = "ï…» "
"Android-SDK-Tools-Licenses" = "ï…» "
"Android-SDK-Tools-Platforms" = "ï…» "
"Android-SDK-Tools-Platforms-Android-29" = "ï…» "
"Android-SDK-Tools-Platforms-Android-30" = "ï…» "
"Android-SDK-Tools-Platforms-Android-31" = "ï…» "
"Android-SDK-Tools-Platforms-Android-32" = "ï…» "
"Android-SDK-Tools-Platforms-Android-33" = "ï…» "
"Android-SDK-Tools-Platforms-Android-34" = "ï…» "
"Android-SDK-Tools-Platforms-Android-35" = "ï…» "
"Android-SDK-Tools-Platforms-Android-36" = "ï…» "
"Android-SDK-Tools-Platforms-Android-37" = "ï…» "
"Android-SDK-Tools-Platforms-Android-38" = "ï…» "
"Android-SDK-Tools-Platforms-Android-39" = "ï…» "
"Android-SDK-Tools-Platforms-Android-40" = "ï…» "
"Android-SDK-Tools-Platforms-Android-41" = "ï…» "
"Android-SDK-Tools-Platforms-Android-42" = "ï…» "
"Android-SDK-Tools-Platforms-Android-43" = "ï…» "
"Android-SDK-Tools-Platforms-Android-44" = "ï…» "

# Important Documents
"Important Documents" = "ïœ˜ï„ª"
"Important-Projects" = "ïˆ ï„ª"
"Important-Scripts" = "ï’‰ ï„ª"
"Important-Downloads" = "ï’˜ ï„ª"

# University
"University" = "ï†œ "
"University-Projects" = "ïˆ ï†œ "

[git_branch]
format = " [$symbol$branch]($style) "
symbol = "ğŸ£ "
style = "bold yellow"

[git_commit]
commit_hash_length = 10
style = "bold white"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
conflicted = "âš”ï¸ "
ahead = "ğŸï¸ ğŸ’¨ Ã—${count}"
behind = "ğŸ¢ Ã—${count}"
diverged = "ğŸ”± ğŸï¸ ğŸ’¨ Ã—${ahead_count} ğŸ¢ Ã—${behind_count}"
untracked = "ğŸ›¤ï¸  Ã—${count}"
stashed = "ğŸ“¦ "
modified = "ğŸ“ Ã—${count}"
staged = "ğŸ—ƒï¸  Ã—${count}"
renamed = "ğŸ“› Ã—${count}"
deleted = "ğŸ—‘ï¸  Ã—${count}"
style = "bright-white"
format = "$all_status$ahead_behind"

[hostname]
ssh_only = true
format = "<[$hostname]($style)>"
trim_at = "-"
style = "bold dimmed white"
disabled = true

[julia]
format = "[$symbol$version]($style) "
symbol = "à®ƒ "
style = "bold green"

[memory_usage]
format = "$symbol[${ram}( | ${swap})]($style) "
threshold = 70
style = "bold dimmed white"
disabled = false

[perl]
symbol = "î© "

[php]
symbol = "î˜ˆ "

[python]
format = "[$symbol$version]($style) "
style = "bold green"
symbol = "î˜† "
pyenv_prefix = "venv "
python_binary = ["./venv/bin/python", "python", "python3", "python2"]
detect_extensions = ["py"]
version_format = "v${raw}"

[gcloud]
format = 'on [$symbol$account(@$domain)(\($project\))]($style) '
symbol = "â˜ï¸  "

[rust]
format = "[$symbol$version]($style) "
style = "bold green"
symbol = "ğŸ¦€ "

[time]
time_format = "%T"
format = "ğŸ•™$time($style) "
style = "bright-white"
disabled = false

[conda]
format = "[$symbol$environment](dimmed green) "
symbol = "ï„Œ "
style="green bold"

[elixir]
symbol = "ğŸ”® "

[swift]
symbol = "ï¯£ "
format = "via [ğŸ  $version](red bold)"

[java]
symbol = "î‰– "

[golang]
symbol = "î˜§ "

[aws]
symbol = "îŒ½  "

[dart]
symbol = "î˜ "

[shell]
fish_indicator = "ïœ¹"
# powershell_indicator = "ï‘ _"
powershell_indicator = "ï…º "
zsh_indicator = "îª…"
bash_indicator = "î¯Š"
unknown_indicator = "mystery shell"
style = "cyan bold"
disabled = false

[sudo]
style = "bold green"
symbol = " ğŸ‘©â€ğŸ’» "
disabled = false

[nodejs]
format = "via [ï¢˜ Node.js $version](bold green) "
detect_files = ["package.json", ".node-version"]
detect_folders = ["node_modules"]

[ruby]
symbol = "îˆ¾ "

[cmake]
symbol = "ï¨¶ "
format = "via [ï¨¶ $version](bold green) "

[haskell]
symbol = "Î» "

[c]
symbol = "î˜ "
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "ïš¤ "
format = '[ $symbol ($version) ]($style)'